sonar.organization=adaptto-live
sonar.projectKey=adaptto-live_adaptto-live-server

# Source and exclusions
sonar.sources=src
sonar.exclusions=**/__tests__/**/*

# Test configuration
sonar.tests=src/__tests__
sonar.test.inclusions=**/__tests__/**/*.ts,**/*.test.ts,**/*.spec.ts

# Coverage configuration
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/__tests__/**/*,jest.config.ts
